### ISSUE TITLE
DM

### ISSUE THREAD

**Issue by MINGDY98** [stove-smooth/sgs-smooth#102]
- [x] DM 상세 UI 완성하기
- [x] DM 채팅 디테일(사진,답장 보내기 등.) 완성하기
-----아래부터 api 연동------
- [x] DM 리스트 가져오기
- [x] DM 생성하기
- [x] DM방 정보 가져오기
- [x] DM방 이름,아이콘 바꾸기
- [x] DM으로 초대장 생성하기
- [x] DM의 초대장으로 서버 들어오기
- [x] DM방에 초대하기
- [x] DM방에서 나가기

**Comment by ruthetum** [comment]
LGTM
