### ISSUE TITLE
[iOS] 커뮤니티&다이렉트 함 UI 개편

### ISSUE THREAD

**Issue by doitduri** [stove-smooth/sgs-smooth#93]
- [  ] 커뮤니티(서버) 리스트 default 값 지정
- [  ] 다이렉트 메시지 > channel board

**Comment by doitduri** [comment]
[pending] 채팅 연결 완료 시 다이렉트 메시지 작업 재개

**Comment by doitduri** [comment]
[pending] 채팅 연결 완료 시 다이렉트 메시지 작업 재개

**Comment by ruthetum** [comment]
LGTM
