### ISSUE TITLE
[iOS] 채팅 기본

### ISSUE THREAD

**Issue by doitduri** [stove-smooth/sgs-smooth#94]
- 채팅 UI
    - [x] 채팅방 UI
    - [x] 채팅 말풍선 
    - [x] 키보드 appearance
- 채팅 기능
    - [  ] 채팅 읽어오기 
    - [x] 채팅 삭제
    - [x] 채팅 보내기
    - [  ] 채팅 수정

**Comment by doitduri** [comment]
#99 채팅 기본 view: mock data로 진행

**Comment by ruthetum** [comment]
LGTM
